from environs import Env

env = Env()
env.read_env()

KEYCLOAK_ISSUER = env.str('KEYCLOAK_ISSUER')
KEYCLOAK_CLIENT_ID = env.str('KEYCLOAK_CLIENT_ID')
KEYCLOAK_CLIENT_SECRET = env.str('KEYCLOAK_CLIENT_SECRET')
KEYCLOAK_AUDIENCE = env.str('KEYCLOAK_AUDIENCE')

OAUTH_TOKEN_URL = f'{KEYCLOAK_ISSUER}/protocol/openid-connect/token'

PORTAL_ENDPOINT = env.str('PORTAL_ENDPOINT')
PORTAL_API_ENDPOINT = f'{PORTAL_ENDPOINT}/api/v1.0'
PORTAL_OUTBOUND_INTEGRATIONS_ENDPOINT = f'{PORTAL_API_ENDPOINT}/integrations/outbound/configurations'

# Settings for caching admin portal request/responses
REDIS_HOST = env.str('REDIS_HOST')
REDIS_PORT = env.int('REDIS_PORT', 6739)
REDIS_DB = env.int('REDIS_DB', 3)
# N-seconds window to keep hash of portal api response
REDIS_CHECK_SECONDS = env.int('REDIS_CHECK_SECONDS', 120)

TRANSFORM_SERVICE_ENDPOINT = env.str('TRANSFORM_SERVICE_ENDPOINT')
TRANSFORM_SERVICE_POSITIONS_ENDPOINT = f'{TRANSFORM_SERVICE_ENDPOINT}/streaming/position'

GOOGLE_PUB_SUB_PROJECT_ID = env.str('GOOGLE_PUB_SUB_PROJECT_ID')
GOOGLE_APPLICATION_CREDENTIALS = env.str('GOOGLE_APPLICATION_CREDENTIALS')
STREAMING_SUBSCRIPTION_NAME = env.str('STREAMING_SUBSCRIPTION_NAME')
STREAMING_TRANSFORMED_SUBSCRIPTION_NAME = env.str('STREAMING_TRANSFORMED_SUBSCRIPTION_NAME')
STREAMING_TRANSFORMED_TOPIC_NAME = env.str('STREAMING_TRANSFORMED_TOPIC_NAME')

