serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: gundi-app-sa-b2b9960e@cdip-dev-78ca.iam.gserviceaccount.com
  name: "router-app-sa"
router_app:
  env:
    TRACE_ENVIRONMENT: dev
    GOOGLE_PUB_SUB_PROJECT_ID: cdip-dev-78ca
    CDIP_ADMIN_ENDPOINT: "https://admin.dev.gundiservice.org"
    GUNDI_API_BASE_URL: "https://admin.dev.gundiservice.org"
    REDIS_HOST: "10.3.176.132"
    GCP_PROJECT_ID: cdip-dev-78ca
    GCP_ENVIRONMENT: dev
    BUCKET_NAME: "cdip-files-dev"
retry_long:
  replicaCount: 1
retry_short:
  replicaCount: 1
unprocessed:
  replicaCount: 1
transformed:
  replicaCount: 1