serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: gundi-app-sa-5bbf9d1f@cdip-stage-78ca.iam.gserviceaccount.com
  name: "router-app-sa"
router_app:
  env:
    TRACE_ENVIRONMENT: stage
    GOOGLE_PUB_SUB_PROJECT_ID: cdip-stage-78ca
    CDIP_ADMIN_ENDPOINT: "https://admin.stage.gundiservice.org"
    GUNDI_API_BASE_URL: "https://admin.stage.gundiservice.org"
    REDIS_HOST: "10.243.180.36"
    GCP_PROJECT_ID: cdip-stage-78ca
    GCP_ENVIRONMENT: stage
    BUCKET_NAME: "cdip-files-stage"
retry_long:
  replicaCount: 1
retry_short:
  replicaCount: 1
unprocessed:
  replicaCount: 6
transformed:
  replicaCount: 1