name: Build and deploy router-app
on:
  push:
    branches:
      - main
      - sik-1872

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v3
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/router-app" >> $GITHUB_OUTPUT

  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v1-stable
    needs: vars
    with:
      environment: stage
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  deploy_stage:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v1-stable
    needs: [vars, build]
    with:
      environment: stage
      chart_name: router-app
      chart_version: '0.3.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
