name: Build integration
on:
  push:
    branches:
      - main
      - 'release-**'
      - gundi-2937 # DELETE ME

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/cdip-routing" >> $GITHUB_OUTPUT

  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v2
    needs: vars
    with:
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  dev-deploy:
    uses: PADAS/gundi-workflows/.github/workflows/terragrunt.yml@v2
    with:
      environment: dev
      working_dir: environments/dev
      tg_command: run-all apply
    env:
      TF_VAR_image: "${{ needs.vars.outputs.repository }}:${{ needs.vars.outputs.tag }}"